# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy, and Pandas provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built-in arithmetic functions. In this lab, you will calculate and compare the processing speed required for calculating a dot product using both basic arithmetic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:

- Compare the performance of high-dimensional matrix operations in Numpy vs. pure Python

## Problem 

Write a routine to calculate the dot product between two $200 \times 200$ dimensional matrices using:

a) Pure Python (no libraries)

b) Numpy's `.dot()` method 


### Create two $200 \times 200$ matrices in Python and fill them with random values using `np.random.rand()` 

In [1]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

# Set up the variables
A = np.random.rand(200,200)
B = np.random.rand(200,200)

## Pure Python

* Initialize a zeros-filled `numpy` matrix
* In Python, calculate the dot product using the formula 


$$ \large C_{i,j}= \sum_k A_{i,k}B_{k,j}$$


* Use Python's `timeit` library to calculate the processing time
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an in-depth explanation on how to time a function or routine in Python

**Hint**: Use a nested `for` loop for accessing, calculating, and storing each scalar value in the resulting matrix. 

In [53]:
import numpy as np

A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 
B = np.mat([[2, 7], [1, 2], [3, 6]])

def prod(A,B):
    
    import numpy as np
    
    if A.shape[1] == B.shape[0]:
        m = np.zeros((A.shape[0], B.shape[1]))
    else:
        print("Dot product does not work with this size matrix")
    
    for i in range(0, m.shape[0]):
        for j in range(0, m.shape[1]):
            r = []
            for a in range(0, B.shape[0]):
                r.append(A[i,j] * B[a, j])
                print(r)
            m[i][j] = sum(r)
            
    return m

print(A)
print(B)
prod(A, B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[2 7]
 [1 2]
 [3 6]]
[2]
[2, 1]
[2, 1, 3]
[14]
[14, 4]
[14, 4, 12]
[8]
[8, 4]
[8, 4, 12]
[35]
[35, 10]
[35, 10, 30]
[14]
[14, 7]
[14, 7, 21]
[56]
[56, 16]
[56, 16, 48]
[20]
[20, 10]
[20, 10, 30]
[77]
[77, 22]
[77, 22, 66]


array([[  6.,  30.],
       [ 24.,  75.],
       [ 42., 120.],
       [ 60., 165.]])

In [54]:
import numpy as np
A = np.random.rand(200, 200)
B = np.random.rand(200, 200)

import timeit

# Start the timer
start = timeit.default_timer()

# Matrix multiplication in pure Python
# def prod(A,B):
    
#     import numpy as np
    
#     if A.shape[1] == B.shape[0]:
#         mat = np.zeros(A.shape[0], B.shape[1])
#         continue
#     else:
#         print("Dot product does not work with this size matrix")
    
#     for i in range(0, mat.shape[0]):
#         for j in range(0, mat.shape[1]):
#             r = []
#             for a in range(0, B.shape[0]):
#                 r.append(A[i,j] * B[a, j])
#             mat[i][j] = sum(r)
#     return mat
            

prod = np.zeros((200, 200))

for i in range(prod.shape[0]):
    for j in range(prod.shape[0]):
        for k in range(prod.shape[0]):
            
            prod[i, k] += A[i, j] * B[j, k]

time_spent = timeit.default_timer() - start

print('Pure Python time:', time_spent, 'sec.')

Pure Python time: 8.623384300000907 sec.


## Numpy 
Set the timer and calculate the time taken by the `.dot()` method for multiplying $A$ and $B$ 


In [55]:
# Start the timer
start = timeit.default_timer()

# Matrix multiplication in numpy
prod = A.dot(B)

time_spent = timeit.default_timer() - start
print('Numpy time:', time_spent, 'sec.')

Numpy time: 0.05045040000004519 sec.


### Your comments

## Summary

In this lab, you performed a quick comparison between calculating a dot product in Numpy vs pure Python. You saw that Numpy is computationally much more efficient than pure Python code because of the sophisticated implementation of Numpy source code. You're encouraged to always perform time tests to fully appreciate the use of an additional library in Python. 